version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      #the credentials of the DB should be in a dedicated vault file
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres-data:/tmp/postgres/data